### ISSUE TITLE
On Windows  can use this on Windows 

### ISSUE THREAD

**Issue by oyeanu** [omer73364/uTube#3]
PS C:\Users\oyean> utube
C:\Program Files (x86)\Nodist\bin\node_modules\utube-cli\index.js:3
import inquirer from 'inquirer';
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:749:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11

**Comment by omer73364** [comment]
could you please tell me which version of Node.js you have installed on your machine?
you can get it by typing: 'node -v' in your terminal

**Comment by oyeanu** [comment]
> node -v

PS C:\Users\oyean> node -v
v11.13.0
PS C:\Users\oyean>

**Comment by omer73364** [comment]
it's too old version
update it to the LTS version Node.js 16.17.0

and give me a feedback if it doesn't work

**Comment by oyeanu** [comment]
> it's too old version update it to the LTS version Node.js 16.17.0
> 
> and give me a feedback if it doesn't work

√ - Check internet connection..

----------------  uTube  ----------------

? Enter (video/playlist) url:
Thank you its working Now

**Comment by oyeanu** [comment]
Please add audio mp3 download option Thank you

**Comment by omer73364** [comment]
> Please add audio mp3 download option Thank you 

Soon in coming updates..
